vincent-chpd/bark-buddies

- Gemfile
- Gemfile.lock
- app/models/dog.rb
- app/models/user.rb
- app/views/devise/registrations/new.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/storage.yml
- db/migrate/20240305211446_create_dogs.rb
- db/migrate/20240305211812_add_reference_to_dog.rb
- db/migrate/20240305211958_add_name_to_user.rb
- db/migrate/20240305212020_add_age_to_user.rb
- db/migrate/20240305212038_add_location_to_user.rb
- db/migrate/20240305212055_add_bio_to_user.rb
- db/migrate/20240306071948_create_active_storage_tables.active_storage.rb
- db/schema.rb
- db/seeds.rb
- test/models/dog_test.rb
I have added 
- faker gem 💎 
- cloudinary gem 💎 
- data in seeds  🌱
> Schema setup

- .github/CODEOWNERS
- .gitignore
- app/controllers/dogs_controller.rb
- app/controllers/users_controller.rb
- app/models/dog.rb
- app/models/user.rb
- app/views/dogs/create.html.erb
- app/views/dogs/destroy.html.erb
- app/views/dogs/show.html.erb
- app/views/dogs/update.html.erb
- app/views/users/destroy.html.erb
- app/views/users/index.html.erb
- app/views/users/show.html.erb
- app/views/users/update.html.erb
- config/routes.rb
- db/schema.rb
- test/controllers/dogs_controller_test.rb
- test/controllers/users_controller_test.rb
created users and dogs controller with relative relationship in the model
> first draft routes and controllers for users and dogs

- app/assets/stylesheets/config/_fonts.scss
- db/seeds.rb
Modified seeds file 🌱 
Added random picture for dogs 🐶 
Added random picture for user 👦🏻 
Added new font  🖊️
> added random pictures for user and dogs

- app/assets/stylesheets/config/_fonts.scss
- app/assets/stylesheets/pages/_home.scss
- app/controllers/users_controller.rb
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
Added dashboard pages 〰️ 
Added buddies near me on dashboard page 🐶 
Styled page
> Dashboard buddies

- app/controllers/events_controller.rb
- app/models/event.rb
- app/views/events/index.html.erb
- app/views/pages/home.html.erb
- config/routes.rb
- db/migrate/20240308221210_create_events.rb
- db/migrate/20240308222823_add_title_to_events.rb
- db/migrate/20240308222904_add_description_to_events.rb
- db/migrate/20240308222952_add_location_to_events.rb
- db/migrate/20240308223020_add_date_to_events.rb
- db/migrate/20240308223049_add_user_to_events.rb
- db/schema.rb
- test/channels/application_cable/connection_test.rb
- test/controllers/events_controller_test.rb
- test/models/event_test.rb
> Added events 

- app/assets/stylesheets/components/_chat_page.scss
- app/assets/stylesheets/components/_conversations_index_page.scss
- app/controllers/conversations_controller.rb
- app/controllers/messages_controller.rb
- app/javascript/controllers/conversation_subscription_controller.js
- app/views/conversations/_conversation_card.html.erb
- app/views/conversations/show.html.erb
I fixed the chat styling and now the messages don't overflow, plus when i send a message the chat scrolls down to the last message
> improved chat styling

- app/assets/stylesheets/pages/_user_index.scss
- app/controllers/users_controller.rb
- app/javascript/search_form.js
- app/views/users/index.html.erb
Added responsiveness to the page
> View users

- app/assets/stylesheets/pages/_user_index.scss
- app/controllers/users_controller.rb
- app/javascript/search_form.js
- app/views/shared/_navbar.html.erb
- app/views/users/index.html.erb
Added js for search bar, fixed the rows for the mobile version, added border around the user's profile information
> User indexx

- app/assets/stylesheets/components/_event.scss
- app/controllers/events_controller.rb
- app/models/attendance.rb
- app/models/event.rb
- app/models/user.rb
- app/views/events/index.html.erb
- db/migrate/20240316140113_create_attendances.rb
- db/schema.rb
- db/seeds.rb
- test/models/attendance_test.rb
Events page updated to include search bar and list of events
> events page updated to include search bar and list of events

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_chat_page.scss
- app/assets/stylesheets/components/_community_cards.scss
- app/assets/stylesheets/components/_event.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_dashboard.scss
- app/views/communities/index.html.erb
- app/views/conversations/index.html.erb
- app/views/events/index.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
- app/views/users/index.html.erb
I have made a few style improvement on the dashboard, navbar and chats
> style improvement on dashboard and navbar

- app/assets/stylesheets/components/_navbar.scss
- app/javascript/controllers/notifications_controller.js
- app/views/shared/_navbar.html.erb
Implemented a notification system
> Notifications

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_user_index.scss
- app/views/shared/_navbar.html.erb
- app/views/users/index.html.erb
Added banner to the page, added the same background colour to match others pages, Fixed error message margin so it only displays when the @message is shown,
Changed navbar to 'explore' added margin to make the text closer and added a border around the avatar
> Style fixes

- app/assets/stylesheets/pages/_profile.scss
- app/controllers/users_controller.rb
- app/views/shared/_navbar.html.erb
- app/views/users/show.html.erb
added bck button, added edit profile functionality. Styling on buttons, modals and forms.
> Profile show page

- app/assets/stylesheets/components/_index.scss
- app/views/layouts/application.html.erb
- app/views/users/index.html.erb
Changed the text on user index page which was suggested, Added the files for the footer to be worked on.
> small changes

- app/assets/stylesheets/components/_event.scss
- app/controllers/events_controller.rb
- app/javascript/controllers/attend_controller.js
- app/javascript/controllers/clear_search.js
- app/models/event.rb
- app/views/communities/index.html.erb
- app/views/events/index.html.erb
- app/views/pages/home.html.erb
- db/seeds.rb
updated the events with some front end
> Events branch

- app/assets/stylesheets/components/_event.scss
- app/javascript/controllers/attend_controller.js
- app/views/events/index.html.erb
> updated events page with front-end

- app/assets/stylesheets/pages/_profile.scss
- app/controllers/friendships_controller.rb
- app/views/layouts/application.html.erb
- app/views/users/show.html.erb
carousel working, follow/unfollow function
> lots and lots of work

- app/controllers/conversations_controller.rb
- app/controllers/messages_controller.rb
- app/javascript/controllers/conversation_subscription_controller.js
- app/javascript/controllers/notifications_controller.js
- app/models/message.rb
- app/views/conversations/show.html.erb
- app/views/messages/_message.html.erb
- app/views/messages/_message_content.html.erb
Now the message in the chat is on the proper side straight away
> Notifications bug

- app/controllers/friendships_controller.rb
fixed button to work properly and stay user page who youve unfollowed
> bug fix on follow/unfollow button

- app/assets/stylesheets/components/_event.scss
- app/javascript/controllers/attend_controller.js
- app/views/events/_event_modal.html.erb
- app/views/events/index.html.erb
- db/seeds.rb
> Attend button

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/pages/_profile.scss
- app/controllers/communities_controller.rb
- app/controllers/community_messages_controller.rb
- app/controllers/conversations_controller.rb
- app/controllers/events_controller.rb
- app/controllers/pages_controller.rb
- app/views/communities/index.html.erb
- app/views/communities/show.html.erb
- app/views/pages/home.html.erb
- app/views/users/show.html.erb
- config/environments/development.rb
added bullet gem
fixed all N+1 
added icon on edit profile button
> added bullet gem and fixed all N+1
